name: Daily Market Analysis

on:
  schedule:
    - cron: '0 6 * * *'  # запуск о 06:00 UTC щодня
  workflow_dispatch:  # дозволяє запускати вручну

jobs:
  update-and-generate:
    runs-on: ubuntu-latest

    steps:
    - name: Клонування репозиторію
      uses: actions/checkout@v3

    - name: Налаштування Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Запуск update.py
      run: python3 update.py

    - name: Запуск generate.py
      run: python3 generate.py

  - name: Пуш оновлень
  env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
  run: |
    git config --global user.name 'github-actions'
    git config --global user.email 'actions@github.com'
    git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
    git add index.html
    git commit -m "Автоматичне оновлення сторінки"
    git push
