name: Daily Market Analysis

on:
  schedule:
    - cron: '0 13 * * 1-5'  # Щодня о 13:00 UTC (8:00 NYT)
  workflow_dispatch:        # Можна запускати вручну

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt || true

    - name: Run generate script
      run: python update.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add index.html
        git commit -m "🤖 Автоматичне оновлення: ${{ github.run_id }}" || echo "No changes"
        git push
